_extends: .github

repository:
  #─────────────────────────────────────────────────────────────────────────────
  # "About" section (on Home Page)
  #─────────────────────────────────────────────────────────────────────────────

  # A short description of the repository
  # MUST BE A SINGLE LINE
  description: Truly amazing stuff.

  # A URL with more information about the repository
  homepage: https://google.com

  # A comma-separated list of topics to set on the repository
  topics: dotnet,csharp

  #─────────────────────────────────────────────────────────────────────────────
  # Settings -> General
  # https://github.com/repository-settings/app/blob/master/docs/plugins/repository.md
  # https://docs.github.com/en/rest/repos/repos#update-a-repository
  #─────────────────────────────────────────────────────────────────────────────

  # The name of the repository
  name: .template-0
